[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
anyhow = "1"
bytes = "1"
http = "0.2"
spin-sdk = "5.0"
wit-bindgen = "0.43.0"

[workspace]
